############################################################
#################### Data Preparation ######################
############################################################

input_data: "D:\\BRAND_HUB_PROJECT\\brandhub-capability\\src\\BHC_Capability\\data\\input_data_refined_4.csv"
idv_list: "D:\\BRAND_HUB_PROJECT\\brandhub-capability\\src\\BHC_Capability\\data\\idv_list_.csv"

granularity: 'weekly' #weekly or monthly

data_prep_group_var:
  - "brand"
  - "category"

date_column: "date"
date_format: "%d-%m-%Y"
start_date: "2022-08-01"
end_date: "2024-06-01"

dv_column: "market_share"

null_percentage: 0.5

scaling: "custom"


###### CFA Modeling ######

cfa_sampling_seeding:
- 2
- 3
- 5
- 7
- 11
- 13
- 17
- 19

###### RF Model ######
model_type: "RandomForest"
model_config:
  RandomForest:
    grid_search:
      max_depth: [2, 3, 4]
      n_estimators: [15, 50, 100, 300, 500]
      max_features: [2, 4, 10]
      random_state: [42]
      eval_metrics: []
    random_state: 42
  XGBoost:
    grid_search:
      max_depth: [2, 3]
      n_estimators: [100, 500, 1000, 1500]
      learning_rate: [0.01, 0.02]
      random_state: [42]
      eval_metrics: []
    random_state: 42
  RF_Ridge:
    grid_search:
      alpha: [0.001, 0.001, 0.01, 1, 5, 10, 15]
      random_state: [42]
    positive: false
    random_state: 42
  Corr_ridge:
    grid_search:
      alpha: [0.001, 0.01, 0.1, 1, 5, 10]
      random_state: [42]
    positive: false
    random_state: 42
  Brute_force:
    grid_search:
      alpha: [0.001, 0.01, 0.1, 1, 5, 10]
      random_state: [42]
    positive: false
    random_state: 42

cross_validation_number: 4


###### Output Paths ######

# Root directory path (can be the current directory)
root_path: "./"

# Output folder where all output files will be saved
output_folder: "output"

# Paths for specific output data
filtered_data: "filtered_data.csv"
no_null_imputed_data: "no_null_imputed_data.csv"
scaled_data: "scaled_data.csv"
cfa_fit_data: "cfa_fit_data.csv"
rf_fit_data: "rf_fit_data.csv"
rf_act_pred_data: "rf_act_pred_data.csv"