
inputdata_blob_name = 'restricted-published'
dataoperations_name = 'restricted-dataoperations'
outputdata_blob_name = 'general-published'
current_date = datetime.now().strftime("%Y-%m-01")
prev_date = '2024-11-01'
dv_folder = 'scorecard_refresh'

time_granularity = 'weekly'
group_vars = ['vendor', 'brand_group_expanded', 'category', 'date']

platform_type = "local"
main_dir = "./"

apps_dir = 'apps/cmi_brand_hub/'
staging_dir = 'staging/cmi_brand_hub/'
solution_dir = 'solution/cmi_brand_hub/'

# COMMAND ----------

directory_config = {
    "support_dir" : f"{main_dir}{apps_dir}{'brand_health_scorecard_mapping/'}",
    "prev_staging_dir" : f"{main_dir}{staging_dir}{dv_folder}/{prev_date}/",
    "current_staging_dir" : f"{main_dir}{staging_dir}{dv_folder}/{current_date}/"
}

# COMMAND ----------

mapping_config = {
    "metrics_rename_mapping": f"{directory_config['support_dir']}/column_name_mapping_file_updated.csv",
    "inverse_logic_mapping": f"{directory_config['support_dir']}/inverse_metrics_creation_logic.csv",
    "idv_list": f"{directory_config['support_dir']}/idv_list_updated.csv",
    "brand_list": f"{directory_config['support_dir']}/brand_select_list_updated.csv",
    "dashboard_metric_names_mapping": f"{directory_config['support_dir']}/dashborad_metric_names_mapping.xlsx",
    "price_class_mapping": f"{directory_config['support_dir']}/price_class_mapping.csv",
    "panel_rename_mapping" : f"{directory_config['support_dir']}/panel_new_names_mapping.csv"
}


# COMMAND ----------

filter_config = {
    'high_null_count_categories': ['CAT TREATS ONLY','DOG TREATS ONLY'],
    "scaling" : {
        'transform_using_standard_scaler': False,
        'transform_using_min_max_scaler': False,
        'custom_min_max': True,
        'cap_min_max_from_idv_file': True
        },
    'equal_weightage': {
        'give_awareness_metrics_equal_weightage': True,
        'give_advocacy_metrics_equal_weightage': False
    },
    "scaled_score" : {
        "only_pillars" : False
    }
}

# COMMAND ----------

refresh_config = {
    "dv": "market_share",
    "time_granularity" : time_granularity,
    "platform" : platform_type,
    "sql_options": sql_options,
    "start_date" : "2022-01-08",
    "end_date" : "2023-09-30",
    "pillars" : {
        'all_category_pillars': ['awareness_pillar', 'loyalty_pillar', 'advocacy_pillar', 'consideration_pillar'],
        'by_category_pillars': ['brand_perceptions_pillar', 'product_feedback_pillar']
    },
    "weights_models": {
        "CFA": {
            "run": True # only True for now
        },
        "RandomForest": {
            "run": True #default
        },
        "XGBoost": {
            "run": False
        }
    },
    "importance_model": {
        "RandomForest": {
            "run": True #default
        },
        "XGBoost": {
            "run": False
        }
    }
}

# COMMAND ----------

input_config = {
    "current_sales_data": f"{directory_config['current_staging_dir']}raw_input_data/nielsen_rms_data.csv",
    "prev_sales_data": f"{directory_config['prev_staging_dir']}raw_input_data/nielsen_rms_data.csv",
    "current_harmonized_data": f"{directory_config['current_staging_dir']}processed_input_data/harmonized_data_processed.csv",
    "prev_harmonized_data": f"{directory_config['prev_staging_dir']}processed_input_data/harmonized_data_processed.csv"
}